### PR TITLE
doc: Add arbtt-chart to Contributed tools

### PR DESCRIPTION
**Pull request by liskin**
I thought it'd be nice to make this more discoverable…

### CODE REVIEW

**Review by nomeata — APPROVED** [review]

**Comment by liskin** [comment]
Hm, the CI failure is a bit weird. https://github.com/nomeata/arbtt/runs/3279293881 succeeded and used the same version of aeson and unordered-containers, which was my first guess. Yet the JSON is now different.

**Comment by nomeata** [comment]
Already investigating. The problem is the change in https://hackage.haskell.org/package/hashable-1.3.3.0/changelog. Will “fix” by depending on that version of hashable.

**Comment by nomeata** [comment]
https://github.com/nomeata/arbtt/pull/135 might fix it

**Comment by liskin** [comment]
Oh, hashable, forgot about that one.

**Comment by nomeata** [comment]
I also tried aeson first … and then unordered-containers … :-)

**Pull request merged**
