### PR TITLE
Depend on new version of hashable

### PR DESCRIPTION
**Pull request by nomeata**
hashable-1.3.3.0 changes the hashing for `Text`, which affects the JSON
output, which broke our “golden test” strategy testing.

This make sure the new version of hashable is used, and updates the
expected test output.

### CODE REVIEW

**Comment by nomeata** [comment]
Odd, still fails

**Comment by nomeata** [comment]
@liskin, any obvoius ideas? I updated the output with what I got locally.

**Comment by nomeata** [comment]
Or I should just do the proper thing and instruct aeson which field order I want.

**Comment by nomeata** [comment]
Hmm, unlike `yaml` it seems that `aeson` doesn’t have support for a field ordering function. So maybe this is the way to go: https://stackoverflow.com/a/37866226/946226

**Comment by liskin** [comment]
I way away to a meeting, but I wouldn't have had any ideas, this is a problem I haven't encountered in Haskell before.
The solution you ended up with seems reasonable. Kudos!

**Pull request merged**
